### PR TITLE
Fix typos with eslint

### PR DESCRIPTION
**Pull request by xissy**
I have removed all warnings with `npm run lint`. Tested in Chrome, IE10.

### CODE REVIEW

**Comment by xissy** [comment]
For the overrided `this.props.pushPath` variable for auth/login, isn't there a better/elegant way? I just added `/* eslint-disable no-shadow */` line above it.

**Comment by xissy** [comment]
As you commented, I amended this with eslint-disable `CookieDough()`.

**Comment by pitzcarraldo** [comment]
How about this way?

``` js
import React, { Component, PropTypes } from 'react';
import { connect } from 'react-redux';
import { pushPath } from 'redux-simple-router';

export default function requireAuth(ComposedComponent) {
  class AuthComponent extends Component {
    static propTypes = {
      user: PropTypes.object,
      location: PropTypes.object,
      push: PropTypes.func.isRequired
    };
...
    handleAuth(props) {
      /* eslint-disable no-shadow */
      const { user, push } = props;
      if (!user) {
        push(`/login?next=${this.props.location.pathname}`);
      }
    }
...
  return connect(state =>({ user: state.auth.user }), { push: pushPath })(AuthComponent);
}
```

Because **redux-simple-router** was changed to **react-router-redux** and [`pushPath()` changed to `reouteActions.push()`](https://github.com/reactjs/react-router-redux#routeactions). And it will be appiled to Reduxible 0.2.0 release. So that application codes also have to changed little when apply Reduxible 0.2.0. To reduce changes for the futrue, we could prepare something to it. If we change that like above, next codes would be changed only two lines.

``` js
import { routeActions } from 'react-router-redux'
...
  return connect(state =>({ user: state.auth.user }), { push: routeActions.push })(AuthComponent);
}
```

**Comment by xissy** [comment]
It sounds like a plan. I pushed the temporary solution code.

**Comment by pitzcarraldo** [comment]
Good job, Thanks to your work. :clap:

**Pull request merged**
